# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe6fd9e3514969a2900c99bd28e683b06a054e4fd19529a57e51b3804c10bfa724dda23eb0b5da6c7c26c4ac95f58d39035460d404455cb36ed70f73b12968de

test:
  secret_key_base: b87e988c615a200273298af2d0f8dcb22f4c83d19e5adce0d1d417eaaf73fe809571e212d57de27eae90e364d50c4ab2964f6d994a8b80170c64492e3d72ff9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
